### ISSUE TITLE
Modify index.html to make UI responsive and nice looking

### ISSUE THREAD

**Issue by dcbriccetti** [dcbriccetti/laser-name-cards#2]

**Comment by vinkaks** [comment]
Is there a static design Figma/AI etc already done for the interface?

**Comment by dcbriccetti** [comment]
Hi. No. What would you recommend?

**Comment by vinkaks** [comment]
If you have a sketch of the idea of the layout I can do the Figma. A couple of design references would help too.

**Comment by dcbriccetti** [comment]
This would have been fun to do, but I’ve already implemented a UI. I still welcome your input.
